name: lint
run-name: Installs project and runs linting
on: [ push, pull_request ]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20 ]
    name: Linting on Ubuntu with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm install
      - run: npm run lint