name: run-tests
run-name: Installs project and runs project tests
on: [ push, pull_request ]
jobs:
  run-tests-nix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20, 22 ]
    name: Tests on Ubuntu with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm install
      - run: npm run test
  run-tests-win:
    runs-on: windows-latest
    strategy:
      matrix:
        node: [ 20, 22 ]
    name: Tests on Windows with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm install
      - run: npm run test